package com.codename1.demos.alphabetscroll;


import com.codename1.components.MultiButton;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Button;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.LayeredLayout;
import com.codename1.util.CaseInsensitiveOrder;
import java.util.Arrays;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Alphabet {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        String[] characters = { "Tyrion Lannister", "Jaime Lannister", "Cersei Lannister", "Daenerys Targaryen",
            "Jon Snow", "Petyr Baelish", "Jorah Mormont", "Sansa Stark", "Arya Stark", "Theon Greyjoy",
            "Bran Stark", "Sandor Clegane", "Joffrey Baratheon", "Catelyn Stark", "Robb Stark", "Ned Stark",
            "Robert Baratheon", "Viserys Targaryen", "Varys", "Samwell Tarly", "Bronn","Tywin Lannister",
            "Shae", "Jeor Mormont","Gendry","Tommen Baratheon","Jaqen H'ghar","Khal Drogo","Davos Seaworth", 
            "Melisandre","Margaery Tyrell","Stannis Baratheon","Ygritte","Talisa Stark","Brienne of Tarth","Gilly",
            "Roose Bolton","Tormund Giantsbane","Ramsay Bolton","Daario Naharis","Missandei","Ellaria Sand",
            "The High Sparrow","Grand Maester Pycelle","Loras Tyrell","Hodor","Gregor Clegane","Meryn Trant",
            "Alliser Thorne","Othell Yarwyck","Kevan Lannister","Lancel Lannister","Myrcella Baratheon",
            "Rickon Stark","Osha","Janos Slynt","Barristan Selmy","Maester Aemon","Grenn","Hot Pie",
            "Pypar","Rast","Ros","Rodrik Cassel","Maester Luwin","Irri","Doreah","Eddison Tollett","Podrick Payne",
            "Yara Greyjoy","Selyse Baratheon","Olenna Tyrell","Qyburn","Grey Worm","Meera Reed","Shireen Baratheon",
            "Jojen Reed","Mace Tyrell","Olly","The Waif","Bowen Marsh"
        };

        Toolbar.setGlobalToolbar(true);

        Form f = new Form("Letter Scroll", new LayeredLayout());  
        
        f.setScrollable(false);
        Container characterContainer = new Container(BoxLayout.y());
        Container lettersContainer = new Container(BoxLayout.y());
        characterContainer.setScrollableY(true);
        lettersContainer.setScrollableY(true);
        
        char lastLetter = 0;
        Arrays.sort(characters, new CaseInsensitiveOrder());
        for(String character : characters) {
            MultiButton mb = new MultiButton(character);
            characterContainer.add(mb);
            char c = Character.toUpperCase(character.charAt(0));
            if(c != lastLetter) {
                lastLetter = c;
                Button btn = new Button("" + lastLetter);
                lettersContainer.add(btn);
                btn.getAllStyles().setPadding(0, 0, 0, 0);
                btn.getAllStyles().setMargin(0, 0, 0, 0);
                btn.addActionListener(e -> {
                    for(Component cmp : characterContainer) {
                        MultiButton m = (MultiButton)cmp;
                        if(Character.toUpperCase(m.getTextLine1().charAt(0)) == c) {
                            m.requestFocus();
                            return;
                        }
                    }
                });
            }
        }
        
        f.add(characterContainer).
                add(BorderLayout.east(lettersContainer));
        
        f.show();                        
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }
}
